### ISSUE TITLE
Modules id'd by multiple slashes work locally but not through browserify-cdn

### ISSUE THREAD

**Issue by jouni-kantola** [jesusabdullah/browserify-cdn#95]
I posted the following issue to RequireBin:
[Node modules id'd by multiple slashes does not work](https://github.com/maxogden/requirebin/issues/68)

As I explained in the issue w/ RequireBin, with packages and Browserify locally everything bundles fine. A simpler example which works locally, but not at RequireBin, is the following oneliner:
```javascript
var VText = require('virtual-dom/vnode/vtext'); window.requiredModule = VText;
```

The package I'm using, from which modules fail to load is:
[virtual-dom](https://www.npmjs.com/package/virtual-dom)

**Comment by jesusabdullah** [comment]
Can confirm this barfs pretty hard: http://wzrd.in/standalone/virtual-dom%2Fvnode%2Fvtext This is likely a bug in subfile support. Some relevant code:

https://github.com/jesusabdullah/browserify-cdn/blob/master/bundler/browserify.js#L13-L15
https://github.com/jesusabdullah/browserify-cdn/blob/master/singular.js#L20 (also L31-L35)

**Comment by jesusabdullah** [comment]
Adding https://github.com/jesusabdullah/browserify-cdn/commit/97aa2104fb26e26688db221b685c4ad92d6b89b1 at least makes it so wzrd.in doesn't hard crash. It says spawn ENOENT? Not sure why it wouldn't work in this case though.

**Comment by h0ke** [comment]
I think this was introduced here: https://github.com/jesusabdullah/browserify-cdn/commit/19836b781ac7c711a95b8acf5b07c2cdc9630ef5#diff-3d19073b28fcfb2374981b7219617866R54

When `spawn` attempts to `cwd` into `module`, it can't since module now includes the subfile. I'd suggest something like below. I'm not 100% sure what the above commit was trying to achieve, but I think this should still cover it.

```
diff --git a/bundler/browserify.js b/bundler/browserify.js
index 5e9273e..3747991 100644
--- a/bundler/browserify.js
+++ b/bundler/browserify.js
@@ -8,7 +8,8 @@ module.exports = function (env, options, cb) {
 
   var argv = [],
       file,
-      module = options.module;
+      module = options.module,
+      module_base = options.module;
 
   if (options.subfile) {
     module += '/' + options.subfile;
@@ -51,7 +52,7 @@ module.exports = function (env, options, cb) {
     }
 
     env.log.info('browserify: running browserify with options: `' + JSON.stringify(argv) + '`...');
-    var bfy = env.spawn('browserify', argv, { cwd: 'node_modules/' + module });
+    var bfy = env.spawn('browserify', argv, { cwd: 'node_modules/' + module_base });
 
     gatherOutputs('browserify', bfy, function (err, data) {
       if (err) {
```

**Comment by jesusabdullah** [comment]
I agree, this looks like the breaking change.

I'll give your suggested approach a try and see how it goes.

**Comment by jesusabdullah** [comment]
Fixed on master. Thanks for the assist @h0ke !
